version: '3.3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8089:8089/udp"
      - "8086:8086"
    env_file:
      - '/opt/security/influxdb.env'
    volumes:
      - /mnt/disks/influxdb:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "80:3000"
#    env_file:
#      - '/opt/security/grafana.env'
    links:
      - influxdb
    volumes:
      - grafana_volume:/var/lib/grafana
  
volumes:
  grafana_volume: {}
