services:
  influxdb:
    image: influxdb:1.11
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8089:8089/udp" # REMEMBER TO WHITELIST IN FIREWALL!
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: "${INFLUXDB_ROOT_PASSWORD}" # REMEMBER TO EXPORT THIS ONE
      DOCKER_INFLUXDB_INIT_ORG: berxa
      DOCKER_INFLUXDB_INIT_BUCKET: monitoring
      DOCKER_INFLUXDB_INIT_RETENTION: 50w
      INFLUXDB_UDP_ENABLED: true
      INFLUXDB_UDP_DATABASE: monitoring
    volumes:
      - influx_data_volume:/var/lib/influxdb
      - influx_config_volume:/etc/influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "80:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_volume:/var/lib/grafana
    links:
      - influxdb # So we can query http://influxdb:8086 from grafana
    restart: always

volumes:
  grafana_volume: {}
  influx_data_volume: {}
  influx_config_volume: {}